//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHOADON
    {
        public int ID_HoaDon { get; set; }
        public int ID_DienThoai { get; set; }
        public int soLuongMua { get; set; }
        public int ID_User { get; set; }
    
        public virtual DIENTHOAI DIENTHOAI { get; set; }
        public virtual HOADON HOADON { get; set; }
        public virtual USER USER { get; set; }
    }
}
