//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIENTHOAI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIENTHOAI()
        {
            this.CTHOADONs = new HashSet<CTHOADON>();
        }
    
        public int ID_dienThoai { get; set; }
        public string tenDienThoai { get; set; }
        public int soLuongTon { get; set; }
        public Nullable<decimal> donGia { get; set; }
        public string hinhAnh { get; set; }
        public string moTa { get; set; }
        public int ID_LoaiDT { get; set; }
        public int ID_HangDT { get; set; }
        public string ghiChu { get; set; }
        public Nullable<System.DateTime> hanBaoHanh { get; set; }
        public string thongSoKyThuat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHOADON> CTHOADONs { get; set; }
        public virtual HANGDT HANGDT { get; set; }
        public virtual LOAIDT LOAIDT { get; set; }
    }
}
