//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.CTHOADONs = new HashSet<CTHOADON>();
        }
    
        public int ID_User { get; set; }
        public string taiKhoan { get; set; }
        public string matKhau { get; set; }
        public string email { get; set; }
        public string SDT { get; set; }
        public Nullable<bool> gioitinh { get; set; }
        public string tenNhanVien { get; set; }
        public string diaChi { get; set; }
        public int role { get; set; }
        public int luong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHOADON> CTHOADONs { get; set; }
        public virtual ROLE ROLE1 { get; set; }
    }
}
